### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by MichaelYochpaz** [Saoneth/plex-custom-audio#12]
Hey, first off I'd like to thank you for the project, the idea is great and can save me a lot of time by avoiding the need to manually mux dubbed audio tracks.

I tried to install the plugin but encountered an issue, would be happy for some help.

The README says to run `curl https://raw.githubusercontent.com/Saoneth/plex-custom-audio/master/install.sh | sudo bash` in the Plex install folder (I'm not using Docker).

When I run the bash script (I ran it without sudo as I don't have root access, but looking at the script looks like it doesn't actually need root privileges?) in the `Plex Media Server` folder, I get this error message:

> mv: cannot stat 'Plex Transcoder': No such file or directory
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now

Seems like the issue is that there is no "Plex Transcoder" folder in Plex's install folder, not sure where this folder is supposed to be. 

These are the folders existing within the folder:

`Logs, Media, Metadata, Diagnostics, Crash Reports ,Plug-in Support, Codecs ,Cache ,Plug-ins`

I've tried to install it manually by dropping the `Plex Custom Audio Mapper` and `Plex Custom Audio Transcoder` from the releases page in the `Plex Media Server/Plug-in Support/Databases` folder (which is where the `com.plexapp.plugins.library.db` file it seems to require sits).

Runing the scan with `Plex Custom Audio Mapper` does seem to work. It detects the files and Plex adds the additional audio tracks to the media, but whenever I try to playback media with the added track (playing with the original track works fine), I get an error saying:

> Conversion failed. The transcoder exited due to an error.

Would be happy if you could help me understand and fix the issue :)

**Comment by Saoneth** [comment]
Hi!
The issue seems to be that you're trying to install it to the wrong directory. You're looking at app **data** directory. Check if you have files under `/usr/lib/plexmediaserver`, or you can use this command to find proper location: `find / -type f -name 'Plex Media Server' -print -quit`.

Both `Plex Custom Audio Mapper` and `Plex Custom Audio Transcoder` should **not** be in same directory as `com.plexapp.plugins.library.db`.

After installing both commands propertly, test with `Plex Custom Audio Transcoder` if it finds location of `com.plexapp.plugins.library.db`, if not you can create symbolic link with `ln -s /path/to/com.plexapp.plugins.library.db`.

**Comment by joex92** [comment]
Hi, how do I install this on MacOS and Windows?
